export const federal_states: string[] = [
  'BADEN_WURTTEMBERG',
  'BAVARIA',
  'BERLIN',
  'BRANDENBURG',
  'BREMEN',
  'HAMBURG',
  'HESSE',
  'LOWER_SAXONY',
  'MECKLENBURG_WESTERN_POMERANIA',
  'NORTH_RHINE_WESTPHALIA',
  'RHINELAND_PALATINATE',
  'SAARLAND',
  'SAXONY',
  'SAXONY_ANHALT',
  'SCHLESWIG_HOLSTEIN',
  'THURINGIA',
];

export const genders: string[] = ['FEMALE', 'MALE', 'DIVERSE'];

export const education_degrees: string[] = [
  'NONE',
  'HAUPTSCHULE',
  'MITTLERE_REIFE',
  'ABITUR',
  'FACHHOCHSCHULREIFE',
  'DIPLOM',
  'MAGISTER',
  'BACHELOR',
  'MASTER',
  'DOKTOR',
  'GESELLE',
  'MEISTER',
  'EINFACHER_DIENST',
  'MITTLERER_DIENST',
  'GEHOBENER_DIENST',
  'HOEHERER_DIENST',
];
